name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build the app
        run: |
          mvn clean install -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "target/Flight-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/your-app"

      - name: Deploy and Run App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: DB_URL,DB_USERNAME,DB_PASSWORD,JWT_SECRET
          script: |
            echo "Installing Java 21 (Amazon Corretto)..."
            sudo yum install java-21-amazon-corretto -y || true

            echo "Killing any existing Java app..."
            pkill -f 'java -jar' || true

            echo "Checking JAR presence..."
            if [ ! -f /home/ec2-user/your-app/Flight-0.0.1-SNAPSHOT.jar ]; then
              echo "JAR file not found!"
              exit 1
            fi

            echo "Environment Variables Check:"
            echo "DB_URL=$DB_URL"
            echo "DB_USERNAME=$DB_USERNAME"
            echo "DB_PASSWORD is set? [${#DB_PASSWORD}] characters"
            echo "JWT_SECRET is set? [${#JWT_SECRET}] characters"

            echo "Creating .env file..."
            echo "DB_URL=$DB_URL" > /home/ec2-user/your-app/app.env
            echo "DB_USERNAME=$DB_USERNAME" >> /home/ec2-user/your-app/app.env
            echo "DB_PASSWORD=$DB_PASSWORD" >> /home/ec2-user/your-app/app.env
            echo "JWT_SECRET=$JWT_SECRET" >> /home/ec2-user/your-app/app.env

            echo "Starting application..."
            cd /home/ec2-user/your-app
            nohup env $(cat app.env | xargs) java -jar Flight-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

            sleep 10
            echo "Last 10 lines of app.log:"
            tail -n 10 app.log
