name: Deploy Java App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: Flight

      - name: Rename and move JAR to root
        run: |
          mkdir -p deploy-artifact
          cp Flight/target/Flight-0.0.1-SNAPSHOT.jar deploy-artifact/app.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "deploy-artifact/app.jar"
          target: "/home/ec2-user/your-app"
          debug: true

      - name: SSH and Run App on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Installing Java 21..."
            sudo yum install java-21-amazon-corretto -y || true
            echo "Killing any running Java processes..."
            pkill -f 'java -jar' || true
            echo "Running app with environment variables..."
            export DB_URL="${{ secrets.RDS_URL }}"
            echo "DB URL " ${DB_URL}
            export DB_USERNAME="${{ secrets.RDS_USERNAME }}"
            export DB_PASSWORD="${{ secrets.RDS_PASSWORD }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            nohup java -jar /home/ec2-user/your-app/app.jar > /home/ec2-user/your-app/app.log 2>&1 &
            echo "App started. Logs at /home/ec2-user/your-app/app.log"
