name: Deploy Spring Boot App to EC2

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: Flight

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "Flight/target/Flight-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/your-app/"
          overwrite: true

      - name: SSH and Run Application on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            echo "Installing Java 21 if not already installed..."
            sudo yum install java-21-amazon-corretto -y || true
            cd /home/ec2-user/your-app
            java -jar Flight-0.0.1-SNAPSHOT.jar > app.log 2>&1 & disown

            echo "Application started. Logs:"
            sleep 3
            tail -n 20 /home/ec2-user/your-app/app.log

